### ISSUE TITLE
Scriptable/non-interactive use.

### ISSUE THREAD

**Issue by mralexgray** [tresni/pyHurricaneDNS#2]
How can we script/issue commands without actually entering into an interactive session... ´á la..

./hurricanednscmd.py username password < $(echo "add domain recordname type 0.0.1.1 \n exit")

**Comment by tresni** [comment]
If you want to do things programmatically you can `import HurricaneDNS` and access everything there.

I never thought about supplying the command via options or anything like that, but it shouldn't be impossible.  If I get a wild hair I'll see what I come up with, otherwise, pull requests readily accepted ;-)

**Comment by tresni** [comment]
Fixed with c18786bfc3797dfb4262da886e2ab4e410f420e2 (I think :) )
